-- MySQL Script generated by MySQL Workbench
-- Tue Apr 14 18:42:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema joshua
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema joshua
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `joshua` DEFAULT CHARACTER SET utf8 ;
USE `joshua` ;

-- -----------------------------------------------------
-- Table `joshua`.`campus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joshua`.`campus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `flag` TEXT(2083) NOT NULL,
  `identifier` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joshua`.`challenge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joshua`.`challenge` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT(500) NOT NULL,
  `difficulty_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  `url` TEXT(2083) NOT NULL,
  `flag` TEXT(2083) NOT NULL,
  `created_on` DATETIME NOT NULL DEFAULT NOW(),
  `updated_on` DATETIME NULL,
  PRIMARY KEY (`id`, `type_id`, `difficulty_id`),
  INDEX `fk_challenge_difficulty_idx` (`difficulty_id` ASC),
  INDEX `fk_challenge_type_idx` (`type_id` ASC),
  CONSTRAINT `fk_challenge_difficulty`
    FOREIGN KEY (`difficulty_id`)
    REFERENCES `joshua`.`difficulty` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_challenge_type`
    FOREIGN KEY (`type_id`)
    REFERENCES `joshua`.`type` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joshua`.`contest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joshua`.`contest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_visible` TINYINT NOT NULL DEFAULT 0,
  `is_actif` TINYINT NOT NULL DEFAULT 0,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT(500) NOT NULL,
  `duration` VARCHAR(45) NOT NULL,
  `created_on` DATETIME NOT NULL DEFAULT NOW(),
  `updated_on` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joshua`.`contest_has_challenge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joshua`.`contest_has_challenge` (
  `contest_id` INT NOT NULL,
  `order` INT NOT NULL,
  `challenge_id` INT NOT NULL,
  PRIMARY KEY (`contest_id`, `challenge_id`),
  INDEX `fk_contest_has_challenge_challenge_idx` (`challenge_id` ASC),
  INDEX `fk_contest_has_challenge_contest_idx` (`contest_id` ASC),
  CONSTRAINT `fk_contest_has_challenge_contest`
    FOREIGN KEY (`contest_id`)
    REFERENCES `joshua`.`contest` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_contest_has_challenge_challenge`
    FOREIGN KEY (`challenge_id`)
    REFERENCES `joshua`.`challenge` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joshua`.`difficulty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joshua`.`difficulty` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `difficulty` VARCHAR(45) NOT NULL,
  `level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `difficulty_UNIQUE` (`difficulty` ASC),
  UNIQUE INDEX `level_UNIQUE` (`level` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joshua`.`specialty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joshua`.`specialty` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `specialty` VARCHAR(45) NOT NULL,
  `identifier` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joshua`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joshua`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `identifier` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joshua`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joshua`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_admin` TINYINT NOT NULL DEFAULT 0,
  `is_actif` TINYINT NOT NULL DEFAULT 0,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `pseudo` VARCHAR(45) NOT NULL,
  `github` VARCHAR(45) NULL,
  `email` VARCHAR(80) NOT NULL,
  `email_confirm` TINYINT NOT NULL DEFAULT 0,
  `password` VARCHAR(45) NOT NULL,
  `specialty_id` INT NOT NULL,
  `campus_id` INT NOT NULL,
  `created_on` DATETIME NOT NULL DEFAULT NOW(),
  `updated_on` DATETIME NULL,
  PRIMARY KEY (`id`, `specialty_id`, `campus_id`),
  INDEX `fk_user_campus_idx` (`campus_id` ASC),
  INDEX `fk_user_specialty_idx` (`specialty_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_user_campus`
    FOREIGN KEY (`campus_id`)
    REFERENCES `joshua`.`campus` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_specialty`
    FOREIGN KEY (`specialty_id`)
    REFERENCES `joshua`.`specialty` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joshua`.`user_has_contest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joshua`.`user_has_contest` (
  `user_id` INT NOT NULL,
  `contest_id` INT NOT NULL,
  `challenge_id` INT NOT NULL,
  `started_on` DATETIME NOT NULL DEFAULT NOW(),
  `ended_on` DATETIME NULL,
  PRIMARY KEY (`user_id`, `contest_id`, `challenge_id`),
  INDEX `fk_user_has_contest_contest_idx` (`contest_id` ASC),
  INDEX `fk_user_has_contest_user_idx` (`user_id` ASC),
  INDEX `fk_user_has_contest_challenge_idx` (`challenge_id` ASC),
  CONSTRAINT `fk_user_has_contest_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `joshua`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_contest_contest`
    FOREIGN KEY (`contest_id`)
    REFERENCES `joshua`.`contest` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_contest_challenge`
    FOREIGN KEY (`challenge_id`)
    REFERENCES `joshua`.`challenge` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `joshua`.`campus`
-- -----------------------------------------------------
START TRANSACTION;
USE `joshua`;
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Bordeaux', 'France', 'france.svg', 'bdx');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Biarritz', 'France', 'france.svg', 'biarritz');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'La Loupe', 'France', 'france.svg', 'loupe');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Lille', 'France', 'france.svg', 'lille');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Lyon', 'France', 'france.svg', 'lyon');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Marseille', 'France', 'france.svg', 'marseille');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Nantes', 'France', 'france.svg', 'nantes');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Orléans', 'France', 'france.svg', 'orleans');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Paris', 'France', 'france.svg', 'paris');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Reims', 'France', 'france.svg', 'reims');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Strasbourg', 'France', 'france.svg', 'strasbourg');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Toulouse', 'France', 'france.svg', 'toulouse');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Tours', 'France', 'france.svg', 'tours');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Amsterdam', 'Netherlands', 'netherlands.svg', 'amsterdam');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Barcelone', 'Spain', 'spain.svg', 'barcelone');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Berlin', 'Germany', 'germany.svg', 'berlin');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Brussels', 'Belgium', 'belgium.svg', 'brussels');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Bucharest', 'Romania', 'romania.svg', 'bucharest');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Budapest', 'Hungary', 'hungary.svg', 'budapest');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Dublin', 'Ireland', 'ireland.svg', 'dublin');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Lisbon', 'Portugal', 'portugal.svg', 'lisbon');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'London', 'England', 'england.svg', 'london');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Madrid', 'Spain', 'spain.svg', 'madrid');
INSERT INTO `joshua`.`campus` (`id`, `city`, `country`, `flag`, `identifier`) VALUES (DEFAULT, 'Milan', 'Italy', 'italy.svg', 'milan');

COMMIT;


-- -----------------------------------------------------
-- Data for table `joshua`.`difficulty`
-- -----------------------------------------------------
START TRANSACTION;
USE `joshua`;
INSERT INTO `joshua`.`difficulty` (`id`, `difficulty`, `level`) VALUES (DEFAULT, 'Easy', '1');
INSERT INTO `joshua`.`difficulty` (`id`, `difficulty`, `level`) VALUES (DEFAULT, 'Medium', '2');
INSERT INTO `joshua`.`difficulty` (`id`, `difficulty`, `level`) VALUES (DEFAULT, 'Hard', '3');
INSERT INTO `joshua`.`difficulty` (`id`, `difficulty`, `level`) VALUES (DEFAULT, 'Pro', '4');
INSERT INTO `joshua`.`difficulty` (`id`, `difficulty`, `level`) VALUES (DEFAULT, 'Nightmare', '5');

COMMIT;


-- -----------------------------------------------------
-- Data for table `joshua`.`specialty`
-- -----------------------------------------------------
START TRANSACTION;
USE `joshua`;
INSERT INTO `joshua`.`specialty` (`id`, `specialty`, `identifier`) VALUES (DEFAULT, 'PHP - Symfony', 'php');
INSERT INTO `joshua`.`specialty` (`id`, `specialty`, `identifier`) VALUES (DEFAULT, 'Java - Angular', 'java');
INSERT INTO `joshua`.`specialty` (`id`, `specialty`, `identifier`) VALUES (DEFAULT, 'React - Node JS', 'js');
INSERT INTO `joshua`.`specialty` (`id`, `specialty`, `identifier`) VALUES (DEFAULT, 'Data Analyst', 'data');

COMMIT;
